id: card_genre_by_decade
type: Card
properties:
  title: Number of Movies by Genre over Time
blocks:
  - id: chart_genres_by_decade
    type: AmCharts4XY
    properties:
      data:
        _request: req_genres_by_decade
      xAxes:
        - type: CategoryAxis
          title:
            text: Decade
          dataFields:
            category: decade
            title:
              text: Decade
      yAxes:
        - type: ValueAxis
          title:
            text: Movies Made
          cursorTooltipEnabled: false
      series:
        _ref:
          path: trends/charts/dynamic_series.yaml
          vars:
            requestName: req_genres_by_decade
            categoryX: decade
            valueYShow: value
            stacked: false
            fillOpacity: 1
            legendItemValueText: "{valueY}"
            tooltipText: "{name}"
      legend:
        type: Legend
      cursor:
        type: XYCursor
        lineY:
          disabled: true
      numberFormatter:
        numberFormat: "#."
