name: genre_by_decade_stacked_card
type: card
label:
  title: Percent of Movies by Genre over Time
blocks:
  - name: chart_genres_by_decade_stacked
    type: amcharts_4_xy
    properties:
      data:
        _request: req_genres_by_decade
      xAxes:
        - type: CategoryAxis
          title:
            text: Decade
          dataFields:
            category: decade
            title:
              text: Decade
      yAxes:
        - type: ValueAxis
          calculateTotals: true
          min: 0
          max: 100
          strictMinMax: true
          cursorTooltipEnabled: false
          title:
            text: Percent of Movies Made
      series:
        _ref:
          path: trends/charts/dynamic_series.yaml
          vars:
            requestName: req_genres_by_decade
            categoryX: decade
            valueYShow: totalPercent
            stacked: true
            fillOpacity: 1
            legendItemValueText: "{valueY.totalPercent}"
            tooltipText: "{name}"
      legend:
        type: Legend
      cursor:
        type: XYCursor
        lineY:
          disabled: true
      numberFormatter:
        numberFormat: "#."
