_mql_aggregate:
  on:
    _request:
      _var: requestName
  pipeline:
    - "$project":
        obj:
          $objectToArray: "$$ROOT"
    - "$unwind":
        path: "$obj"
    - "$group":
        _id: "$obj.k"
        sum:
          "$sum": "$obj.v"
    - "$match":
        _id:
          "$ne":
            _var: categoryX
    - "$sort":
        sum: -1
    - "$project":
        _id: 0
        type: LineSeries
        name: "$_id"
        stacked:
          "$literal":
            _var: stacked
        fillOpacity:
          "$literal":
            _var: fillOpacity
        tooltipText:
          _var: tooltipText
        legendSettings:
          itemValueText:
            _var: legendItemValueText
        dataFields:
          valueY: "$_id"
          valueYShow:
            _var: valueYShow
          categoryX:
            _var: categoryX
